# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15a0ee1d1c86c862cf2d7b6419c86d5c4d4fa33575e8dd88c54d3b43aac9046b6467d35497f9cb0e50809b6fbddbb77f6dfaab3955aad30165206674b5d162de

test:
  secret_key_base: 06780c40a34786ab302aa6a4902e23837f97fe1dbff3d5c835740197daeeab8a2a104fa30c71da0764f21d77cee28cd322b3e44938ab67eda94f0d89659e84c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
